vich_uploader:
    db_driver: orm

    mappings:
        book_image:
            uri_prefix: /images/books
            upload_destination: '%kernel.project_dir%/public/uploads/images/books'
            namer:
                service: vich_uploader.namer_uniqid

            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true